version: '3.4'

services:
  webcat:
    image: webcat
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229
    links:
      - redis
    command: ["node", "--inspect=0.0.0.0:9229", "app.js"]
  redis:
    image: redis:latest
    ports:
      - 6379:6379
